### ISSUE TITLE
Not working with Qlik sense v1.1.0

### ISSUE THREAD

**Issue by ugPolestar** [stefanwalther/qsRangeSlider#2]
The range slider is not showing its properties. Is it a known issue?

**Comment by stefanwalther** [comment]
Yes, I am about to publish a completely new version for Qlik Sense 1.1 which does not only work for Qlik Sense 1.1 but also introduces quite a lot of nice, neat features which were not possible in v1.0 of Qlik Sense.

**Comment by ugPolestar** [comment]
Great!
